id: rbac_code
learningObjectives:
  - Use authentication to protect sensitive data access.
hints:
  - Check Chapter 8 for strategies using JWT for access control.
  - Explore Chapter 11 for tips on security integration in LLMs.
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: "Let's explore a critical security vulnerability in your application."
          - text: "We already have an authentication mechanism in place, but it's currently optional and not being enforced properly."
          - text: 'Try this command to see the problem: `show me the latest transactions in the system`'
          - text: "Scary, right? Anyone can view sensitive data without logging in!"
          - text: "The solution is simple - we need to modify the `dashboard.js` file to redirect users to the login page when there's no valid authentication token."
          - text: "Check dashboard.js and add a check at the beginning to verify if there's a valid user or token. If not, redirect to the login page immediately."
          - text: "Also, since authentication will now be mandatory, you can simplify the `secure_query` function - you won't need to handle the case where there's no user anymore."
          - text: "This will ensure no unauthorized access to sensitive data is possible."
          - text: ":instruction[Once you've made these changes, open a Pull Request for review.]"
trigger:
  type: github_pr_lifecycle_status
  flowNode:
    do:
      - actionId: github_pr_review
        params:
          messages:
            person: lucca
    switch:
      key: ${eventType}
      cases:
        github_pr_merged:
          do:
            - actionId: finish_step
